### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by manuel-rubio** [kvishnivetsky/mod_external_dsp#1]
Looks like when we try to compile and run the current code with the current FreeSwitch version is giving this error:

```
undefined symbol: mod_extenal_dsp_module_interface
```

Any idea to solve it?

**Comment by kvishnivetsky** [comment]
> 
> 
> Looks like when we try to compile and run the current code with the current FreeSwitch version is giving this error:
> 
> ```
> undefined symbol: mod_extenal_dsp_module_interface
> ```
> 
> Any idea to solve it?

I'll take a look. Please, give me some more info about your build environment:
Which FreeSWITCH version do you trying to build(it will be very cool if you give a branch, commit hash, tag)
Which OS name, release.
Commands sequence to represent this issue.

**Comment by manuel-rubio** [comment]
> I'll take a look. Please, give me some more info about your build environment:
> Which FreeSWITCH version do you trying to build(it will be very cool if you give a branch, commit hash, tag)

I was trying with the last version of FreeSwitch (master branch), I think it's still 1.10.

> Which OS name, release.

Debian GNU/Linux, 10 (buster)

> Commands sequence to represent this issue.

I followed the README you have in this project.

**Comment by manuel-rubio** [comment]
@kvishnivetsky any idea?

**Comment by kvishnivetsky** [comment]
@manuel-rubio , Hi. I made fixes in manusl in readme, but, it solves only build issues.
After those fixes I have successfull build in environment like you described.
Is this issue fires during run or during build stage?

**Comment by kvishnivetsky** [comment]
`freeswitch@fs-demo> load mod_external_dsp
+OK Reloading XML
+OK

2021-06-19 21:26:28.983239 [INFO] mod_enum.c:887 ENUM Reloaded
2021-06-19 21:26:28.983239 [INFO] switch_time.c:1430 Timezone reloaded 1750 definitions
2021-06-19 21:26:28.983239 [CONSOLE] switch_loadable_module.c:1803 Successfully Loaded [mod_external_dsp]
2021-06-19 21:26:28.983239 [NOTICE] switch_loadable_module.c:350 Adding Application 'process_audio_start'
2021-06-19 21:26:28.983239 [NOTICE] switch_loadable_module.c:412 Adding API Function 'process_audio'
`

**Comment by kvishnivetsky** [comment]
@manuel-rubio , Could you, please, give me full list of steps to reproduce your issue?

**Comment by manuel-rubio** [comment]
@kvishnivetsky that's happening when I'm using it, it's triggering to me that error:

```
undefined symbol: mod_extenal_dsp_module_interface
```

**Comment by kvishnivetsky** [comment]
> 
> 
> @kvishnivetsky that's happening when I'm using it, it's triggering to me that error:
> 
> ```
> undefined symbol: mod_extenal_dsp_module_interface
> ```

Is it it happening during build from sources or during `freeswitch` process starting up or when you trying to perform `> load mod_external_dsp` in `fs_cli` ?
